"""
Seed script — creates initial users with proper bcrypt hashes.
Run: python seed_data.py

Credentials:
============
HR Accounts:
  hr@company.ru       / HrAdmin2024!
  hr2@company.ru      / HrManager2024!

Candidate Accounts:
  candidate1@mail.ru      / Candidate1Pass!
  candidate2@mail.ru      / Candidate2Pass!
  candidate3@gmail.com    / Candidate3Pass!
  candidate4@yandex.ru    / Candidate4Pass!
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from passlib.context import CryptContext

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


def generate_sql():
    users = [
        ("hr@company.ru", "HrAdmin2024!", "hr", "Иванова Мария Петровна", "+7-495-123-4567"),
        ("hr2@company.ru", "HrManager2024!", "hr", "Смирнов Алексей Дмитриевич", "+7-495-234-5678"),
        ("candidate1@mail.ru", "Candidate1Pass!", "candidate", "Петров Дмитрий Сергеевич", "+7-916-111-2233"),
        ("candidate2@mail.ru", "Candidate2Pass!", "candidate", "Сидорова Елена Александровна", "+7-926-333-4455"),
        ("candidate3@gmail.com", "Candidate3Pass!", "candidate", "Козлов Андрей Викторович", "+7-903-555-6677"),
        ("candidate4@yandex.ru", "Candidate4Pass!", "candidate", "Новикова Анна Игоревна", "+7-915-777-8899"),
    ]

    print("-- Auto-generated seed data with valid bcrypt hashes")
    print("-- Generated by seed_data.py\n")

    for email, password, role, name, phone in users:
        hashed = pwd_context.hash(password)
        print(f"INSERT INTO users (email, password_hash, role, full_name, phone) VALUES")
        print(f"('{email}', '{hashed}', '{role}', '{name}', '{phone}');")
        print(f"-- Password: {password}\n")


if __name__ == "__main__":
    generate_sql()
