import React, { useState, useEffect, useRef } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { MessageCircle, Send, Search, Check, CheckCheck, X } from 'lucide-react';
import { messagesAPI } from '../api/client';
import useAuthStore from '../stores/authStore';
const COLORS=['#3b82f6','#8b5cf6','#ec4899','#f59e0b','#10b981','#ef4444','#06b6d4','#84cc16'];
export default function Messages(){
  const[convs,setConvs]=useState([]);const[sel,setSel]=useState(null);const[msgs,setMsgs]=useState([]);
  const[input,setInput]=useState('');const[showSugg,setShowSugg]=useState(false);const[searchQ,setSearchQ]=useState('');const[searchRes,setSearchRes]=useState([]);
  const user=useAuthStore(s=>s.user);const chatEnd=useRef(null);const pollRef=useRef(null);const navigate=useNavigate();const location=useLocation();
  useEffect(()=>{loadConvs();pollRef.current=setInterval(loadConvs,5000);return()=>clearInterval(pollRef.current)},[]);
  useEffect(()=>{chatEnd.current?.scrollIntoView({behavior:'smooth'})},[msgs]);
  useEffect(()=>{const t=setTimeout(()=>{if(searchQ.trim().length>=2)messagesAPI.searchUsers(searchQ).then(({data})=>setSearchRes(data)).catch(()=>setSearchRes([]));else setSearchRes([])},300);return()=>clearTimeout(t)},[searchQ]);
  const loadConvs=()=>messagesAPI.conversations().then(({data})=>setConvs(data)).catch(()=>{});
  const openChat=async c=>{setSel(c);try{const{data}=await messagesAPI.withUser(c.user_id);setMsgs(data);loadConvs()}catch{}};
  const sendMsg=async()=>{if(!input.trim()||!sel)return;const t=input.trim();setInput('');
    setMsgs(p=>[...p,{id:Date.now(),from_user_id:user.id,content:t,is_read:false,timestamp:new Date().toISOString()}]);
    try{await messagesAPI.send(sel.user_id,t);const{data}=await messagesAPI.withUser(sel.user_id);setMsgs(data)}catch{}};
  const startChat=u=>{const c={user_id:u.id,user_name:u.full_name,user_role:u.role,company_name:null};setSel(c);setSearchQ('');setSearchRes([]);openChat(c)};
  const getAv=(uid,name)=>{const s=localStorage.getItem(`profile_${uid}`);if(s){const p=JSON.parse(s);if(p.photo)return<img src={p.photo} alt="" className="w-10 h-10 rounded-full object-cover"/>}
    return<div className="w-10 h-10 rounded-full flex items-center justify-center text-sm text-gray-900" style={{backgroundColor:COLORS[uid%COLORS.length]}}>{(name||'?')[0]}</div>};
  const filteredConvs=searchQ.trim().length>=2?convs.filter(c=>c.user_name.toLowerCase().includes(searchQ.toLowerCase())):convs;
  return(<div className="h-screen bg-gray-50 text-gray-900 flex">
    <div className="w-80 border-r border-gray-200 flex flex-col">
      <div className="px-4 py-3 border-b border-gray-200 flex items-center justify-between"><h2 className="font-bold flex items-center gap-2"><MessageCircle className="w-5 h-5 text-blue-600"/>Сообщения</h2><button onClick={()=>navigate(-1)} className="text-gray-600 hover:text-gray-900 text-sm" title="Вернуться назад">Назад</button></div>
      <div className="p-2 border-b border-gray-200"><div className="relative"><Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-gray-600"/><input value={searchQ} onChange={e=>setSearchQ(e.target.value)} className="w-full pl-9 pr-8 py-2 bg-white text-sm rounded border border-gray-200 focus:border-blue-500 focus:outline-none" placeholder="Поиск по ФИО..." onFocus={()=>setShowSugg(true)} onBlur={()=>setTimeout(()=>setShowSugg(false),200)}/>
        {searchQ&&<button onClick={()=>{setSearchQ('');setSearchRes([])}} className="absolute right-2 top-1/2 -translate-y-1/2" title="Очистить поиск"><X className="w-4 h-4 text-gray-600"/></button>}</div>
        {(searchRes.length>0||(showSugg&&!searchQ))&&<div className="mt-2 bg-white rounded-lg overflow-hidden border border-gray-200 max-h-60 overflow-y-auto">{searchRes.length>0?searchRes.map(u=>(<button key={u.id} onClick={()=>startChat(u)} className="w-full text-left px-3 py-2 hover:bg-gray-50 flex items-center gap-2 text-sm">{getAv(u.id,u.full_name)}<div><div className="font-medium">{u.full_name}</div><div className="text-xs text-gray-600">{u.role==='hr'?'HR':'Кандидат'}</div></div></button>)):convs.slice(0,5).map(cv=>(<button key={cv.user_id} onClick={()=>openChat(cv)} className="w-full text-left px-3 py-2 hover:bg-gray-50 flex items-center gap-2 text-sm">{getAv(cv.user_id,cv.user_name)}<div className="min-w-0 flex-1"><div className="font-medium">{cv.user_name}</div><div className="text-xs text-gray-600 truncate">{cv.last_message}</div></div>{cv.unread>0&&<span className="bg-blue-600 text-xs rounded-full w-5 h-5 flex items-center justify-center shrink-0">{cv.unread}</span>}</button>))}</div>}</div>
      {/* Conversations list — shown immediately like Telegram */}
      <div className="flex-1 overflow-y-auto max-h-[calc(100vh-200px)]">
        {filteredConvs.length===0&&searchRes.length===0&&<div className="text-center py-10 text-gray-600 text-sm">{searchQ?'Не найдено':'Нет диалогов'}</div>}
        {filteredConvs.map(c=>(<button key={c.user_id} onClick={()=>openChat(c)} className={`w-full text-left px-4 py-3 border-b border-gray-100 hover:bg-white flex items-center gap-3 ${sel?.user_id===c.user_id?'bg-white':''}`} title={`Открыть переписку с ${c.user_name}`}>
          {getAv(c.user_id,c.user_name)}<div className="flex-1 min-w-0"><div className="flex justify-between"><div><span className="font-medium text-sm">{c.user_name}</span>{c.company_name&&<span className="text-xs text-gray-600 ml-1">· {c.company_name}</span>}</div>
            {c.unread>0&&<span className="bg-blue-600 text-xs rounded-full w-5 h-5 flex items-center justify-center">{c.unread}</span>}</div><p className="text-xs text-gray-600 truncate">{c.last_message}</p></div></button>))}</div></div>
    <div className="flex-1 flex flex-col">
      {sel?(<><div className="px-5 py-3 border-b border-gray-200 flex items-center gap-3">{getAv(sel.user_id,sel.user_name)}<div className="flex-1"><div className="font-medium">{sel.user_name}</div><div className="text-xs text-gray-600">{sel.user_role==='hr'?'HR-менеджер':'Кандидат'}{sel.company_name&&` · ${sel.company_name}`}</div></div><button onClick={()=>navigate(`/user/${sel.user_id}`)} className="px-3 py-1.5 bg-gray-200 hover:bg-gray-300 rounded text-xs" title="Открыть профиль пользователя">Профиль</button></div>
        <div className="flex-1 overflow-y-auto p-4 space-y-3">{msgs.map(m=><div key={m.id} className={`flex ${m.from_user_id===user?.id?'justify-end':'justify-start'}`}><div className={`max-w-[70%] px-4 py-2.5 rounded-2xl text-sm ${m.from_user_id===user?.id?'bg-blue-600 rounded-br-md':'bg-gray-200 rounded-bl-md'}`}>{m.from_user_id!==user?.id&&<div className="text-xs opacity-60 mb-0.5">{sel?.user_name}</div>}{m.content.startsWith('📋')?<div onClick={()=>{const match=m.content.match(/(user|vacancy)\/([0-9]+)/);if(match)navigate(`/${match[1]==='user'?'user':'vacancy'}/${match[2]}`)}} className="bg-gray-300/50 rounded-lg p-3 cursor-pointer hover:bg-gray-300 transition"><div className="text-sm font-medium">{m.content.split('\n')[0]}</div><div className="text-xs text-blue-600 mt-1">Нажмите чтобы открыть →</div></div>:<div className="whitespace-pre-wrap">{m.content}</div>}<div className="text-[10px] text-gray-600 mt-1 text-right flex items-center justify-end gap-1">{new Date(m.timestamp).toLocaleTimeString('ru',{hour:'2-digit',minute:'2-digit'})}{m.from_user_id===user?.id&&(m.is_read?<CheckCheck className="w-3 h-3 text-blue-600"/>:<Check className="w-3 h-3"/>)}</div></div></div>)}<div ref={chatEnd}/></div>
        <div className="p-3 border-t border-gray-200">
        {user?.role==='hr'&&<div className="flex flex-wrap gap-1 mb-2">{[{l:'Приглашение',t:'Добрый день! Приглашаем на следующий этап собеседования.'},{l:'Отказ',t:'Благодарим за участие. К сожалению, выбор пал на другого кандидата.'},{l:'Оффер',t:'Поздравляем! Хотим предложить вам позицию. Ожидайте оффер на email.'}].map((t,i)=><button key={i} onClick={()=>setInput(t.t)} className="text-[10px] px-2 py-1 rounded-full border border-gray-200 text-gray-600 hover:border-blue-500 hover:text-blue-600" title={t.l}>{t.l}</button>)}</div>}
        <div className="flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendMsg()} className="flex-1 bg-gray-50 border border-gray-300 rounded-full px-4 py-2.5 text-sm focus:outline-none focus:border-blue-500" placeholder="Написать сообщение..."/><button onClick={sendMsg} disabled={!input.trim()} className="p-2.5 bg-blue-600 rounded-full hover:bg-blue-700 disabled:opacity-50" title="Отправить сообщение"><Send className="w-4 h-4"/></button></div></div>
      </>):(<div className="flex-1 flex items-center justify-center text-gray-600"><div className="text-center"><MessageCircle className="w-12 h-12 mx-auto mb-3 opacity-30"/><p>Выберите диалог или найдите пользователя</p></div></div>)}</div>
  </div>);
}
