"""Full seed: admin, companies, HR, candidates, interviews, chat, submissions, messages, anticheat."""
import logging
from datetime import datetime, timedelta
from sqlalchemy import select, func
from app.database import AsyncSessionLocal
from app.models import *
from app.auth.jwt_utils import hash_password
logger = logging.getLogger(__name__)

async def seed_database():
    async with AsyncSessionLocal() as db:
        if (await db.execute(select(func.count(User.id)))).scalar() > 0:
            logger.info("DB already seeded"); return
        logger.info("Seeding database...")
        now = datetime.utcnow()

        # Companies
        c1 = Company(name="TechVision Labs", description="AI/ML решения для бизнеса", website="https://techvision.example.com")
        c2 = Company(name="DataFlow Solutions", description="Платформа аналитики и BI", website="https://dataflow.example.com")
        db.add_all([c1, c2]); await db.flush()

        # Admin
        admin = User(email="admin@platform.ru", password_hash=hash_password("Admin2024!"), role=UserRole.ADMIN, full_name="Администратор Системы", phone="+7-800-100-0000")
        db.add(admin); await db.flush()

        # HR
        hr1 = User(email="hr@company.ru", password_hash=hash_password("HrAdmin2024!"), role=UserRole.HR, full_name="Иванова Мария Петровна", phone="+7-495-123-4567", company_id=c1.id)
        hr2 = User(email="hr2@company.ru", password_hash=hash_password("HrManager2024!"), role=UserRole.HR, full_name="Смирнов Алексей Дмитриевич", phone="+7-495-234-5678", company_id=c2.id)
        db.add_all([hr1, hr2]); await db.flush()

        # Vacancies
        vacs = [
            Vacancy(company_id=c1.id, title="Python Backend Developer", specialty="developer", level="middle", description="FastAPI, PostgreSQL, Docker. Удалённая работа. Команда из 8 человек.", salary_from=150000, salary_to=250000),
            Vacancy(company_id=c1.id, title="DevOps Engineer", specialty="devops", level="middle", description="Kubernetes, CI/CD, Terraform, мониторинг. Гибридный график.", salary_from=180000, salary_to=300000),
            Vacancy(company_id=c1.id, title="QA Engineer", specialty="qa", level="junior", description="Ручное и автоматизированное тестирование, pytest, Selenium.", salary_from=80000, salary_to=150000),
            Vacancy(company_id=c2.id, title="Аналитик данных", specialty="analyst", level="middle", description="SQL, Python, Tableau, A/B тесты, метрики продукта.", salary_from=120000, salary_to=200000),
            Vacancy(company_id=c2.id, title="Junior Python Developer", specialty="developer", level="junior", description="Python, REST API, базовые алгоритмы. Менторство.", salary_from=60000, salary_to=100000),
            Vacancy(company_id=c2.id, title="Senior Data Scientist", specialty="data_science", level="senior", description="ML, deep learning, NLP, MLOps. Лидирование проектов.", salary_from=250000, salary_to=400000),
        ]
        for v in vacs: db.add(v)
        await db.flush()

        # Support agents
        sup1 = User(email="support1@platform.ru", password_hash=hash_password("Support2024!"), role=UserRole.SUPPORT, full_name="Васильев Олег Николаевич", phone="+7-800-200-0001", email_verified=True)
        sup2 = User(email="support2@platform.ru", password_hash=hash_password("Support2024!"), role=UserRole.SUPPORT, full_name="Романова Ксения Андреевна", phone="+7-800-200-0002", email_verified=True)
        db.add_all([sup1, sup2]); await db.flush()

        # Candidates — 6 total (3 per company)
        cdata = [
            ("candidate1@mail.ru","Candidate1Pass!","Петров Дмитрий Сергеевич","+7-916-111-2233"),
            ("candidate2@mail.ru","Candidate2Pass!","Сидорова Елена Александровна","+7-926-333-4455"),
            ("candidate3@gmail.com","Candidate3Pass!","Козлов Андрей Викторович","+7-903-555-6677"),
            ("candidate4@yandex.ru","Candidate4Pass!","Новикова Анна Игоревна","+7-915-777-8899"),
            ("candidate5@mail.ru","Candidate5Pass!","Федоров Сергей Павлович","+7-903-444-5566"),
            ("candidate6@gmail.com","Candidate6Pass!","Кузнецова Мария Владимировна","+7-916-222-3344"),
        ]
        cands = []
        for e,p,n,ph in cdata:
            u = User(email=e, password_hash=hash_password(p), role=UserRole.CANDIDATE, full_name=n, phone=ph, email_verified=True)
            db.add(u); cands.append(u)
        await db.flush()
        logger.info(f"Created {len(cands)+5} users, 2 companies, {len(vacs)} vacancies")

        # Task bank — 64 templates: developer, analyst, devops, qa, data_science
        tpls = [
            TaskTemplate(title="Сумма массива",domain=TaskDomain.ARRAYS,level=DifficultyLevel.JUNIOR,description="Найдите сумму элементов массива.",input_format="n, массив",output_format="сумма",reference_solution='n=int(input())\na=list(map(int,input().split()))\nprint(sum(a))',visible_tests=[{"input": "5\n1 2 3 4 5", "expected": "15"}],hidden_tests=[{"input": "1\n42", "expected": "42"}],constraints="n<=10^5"),
            TaskTemplate(title="Максимальный элемент",domain=TaskDomain.ARRAYS,level=DifficultyLevel.JUNIOR,description="Дан массив из n целых чисел. Найдите и выведите максимальный элемент массива.",input_format="n, массив",output_format="max",reference_solution='n=int(input())\nprint(max(list(map(int,input().split()))))',visible_tests=[{"input": "5\n3 1 4 1 5", "expected": "5"}],hidden_tests=[{"input": "1\n0", "expected": "0"}],constraints="n<=10^5"),
            TaskTemplate(title="Проверка палиндрома",domain=TaskDomain.STRINGS,level=DifficultyLevel.JUNIOR,description="Дана строка. Определите, является ли она палиндромом (читается одинаково в обе стороны). Выведите YES если палиндром, NO иначе.",input_format="строка",output_format="YES/NO",reference_solution='s=input()\nprint(\'YES\' if s==s[::-1] else \'NO\')',visible_tests=[{"input": "abcba", "expected": "YES"}],hidden_tests=[{"input": "a", "expected": "YES"}],constraints="|s|<=10^5"),
            TaskTemplate(title="Числа Фибоначчи",domain=TaskDomain.MATH,level=DifficultyLevel.JUNIOR,description="Дано число n. Выведите первые n чисел последовательности Фибоначчи через пробел. F(1)=1, F(2)=1, F(n)=F(n-1)+F(n-2).",input_format="n",output_format="числа",reference_solution='n=int(input())\nf=[1,1]\nfor i in range(2,n):f.append(f[-1]+f[-2])\nprint(*f[:n])',visible_tests=[{"input": "5", "expected": "1 1 2 3 5"}],hidden_tests=[{"input": "1", "expected": "1"}],constraints="n<=45"),
            TaskTemplate(title="Сортировка массива",domain=TaskDomain.SORTING,level=DifficultyLevel.JUNIOR,description="Дан массив из n целых чисел. Отсортируйте его по возрастанию и выведите результат.",input_format="n, массив",output_format="отсортированный",reference_solution='n=int(input())\na=list(map(int,input().split()))\na.sort()\nprint(*a)',visible_tests=[{"input": "5\n5 3 1 4 2", "expected": "1 2 3 4 5"}],hidden_tests=[{"input": "1\n1", "expected": "1"}],constraints="n<=1000"),
            TaskTemplate(title="Факториал",domain=TaskDomain.MATH,level=DifficultyLevel.JUNIOR,description="Дано число n. Вычислите факториал n! (произведение всех чисел от 1 до n). Для n=0 факториал равен 1.",input_format="n",output_format="n!",reference_solution='n=int(input())\nr=1\nfor i in range(1,n+1):r*=i\nprint(r)',visible_tests=[{"input": "5", "expected": "120"}],hidden_tests=[{"input": "0", "expected": "1"}],constraints="n<=20"),
            TaskTemplate(title="Реверс строки",domain=TaskDomain.STRINGS,level=DifficultyLevel.JUNIOR,description="Дана строка. Выведите её в обратном порядке (последний символ первым и т.д.).",input_format="строка",output_format="обратная",reference_solution='print(input()[::-1])',visible_tests=[{"input": "hello", "expected": "olleh"}],hidden_tests=[{"input": "a", "expected": "a"}],constraints="|s|<=10^5"),
            TaskTemplate(title="Чётные числа",domain=TaskDomain.ARRAYS,level=DifficultyLevel.JUNIOR,description="Дан массив из n целых чисел. Выведите через пробел только чётные числа в порядке их появления.",input_format="n, массив",output_format="чётные",reference_solution='n=int(input())\nprint(*[x for x in map(int,input().split()) if x%2==0])',visible_tests=[{"input": "6\n1 2 3 4 5 6", "expected": "2 4 6"}],hidden_tests=[{"input": "1\n1", "expected": ""}],constraints="n<=10^5"),
            TaskTemplate(title="Простое число",domain=TaskDomain.MATH,level=DifficultyLevel.JUNIOR,description="Дано натуральное число n. Определите, является ли оно простым (делится только на 1 и на себя). Выведите YES или NO.",input_format="n",output_format="YES/NO",reference_solution='n=int(input())\nprint(\'YES\' if n>1 and all(n%i for i in range(2,int(n**0.5)+1)) else \'NO\')',visible_tests=[{"input": "7", "expected": "YES"}],hidden_tests=[{"input": "1", "expected": "NO"}],constraints="n<=10^6"),
            TaskTemplate(title="Уникальные элементы",domain=TaskDomain.ARRAYS,level=DifficultyLevel.JUNIOR,description="Уникальные с сохранением порядка.",input_format="n, массив",output_format="уникальные",reference_solution='n=int(input())\na=list(map(int,input().split()))\ns=set();r=[]\nfor x in a:\n if x not in s:s.add(x);r.append(x)\nprint(*r)',visible_tests=[{"input": "7\n1 2 3 2 1 4 3", "expected": "1 2 3 4"}],hidden_tests=[{"input": "1\n5", "expected": "5"}],constraints="n<=10^5"),
            TaskTemplate(title="Среднее арифметическое",domain=TaskDomain.ARRAYS,level=DifficultyLevel.JUNIOR,description="Дан массив из n вещественных чисел. Вычислите среднее арифметическое и выведите результат, округлённый до 2 знаков после запятой.",input_format="n, массив",output_format="среднее",reference_solution='n=int(input())\na=list(map(float,input().split()))\nprint(round(sum(a)/n,2))',visible_tests=[{"input": "4\n1 2 3 4", "expected": "2.5"}],hidden_tests=[{"input": "1\n5", "expected": "5.0"}],constraints="n<=10^5"),
            TaskTemplate(title="Количество слов",domain=TaskDomain.STRINGS,level=DifficultyLevel.JUNIOR,description="Дана строка, содержащая слова, разделённые пробелами. Подсчитайте количество слов и выведите число.",input_format="строка",output_format="число",reference_solution='print(len(input().split()))',visible_tests=[{"input": "Hello World", "expected": "2"}],hidden_tests=[{"input": "one", "expected": "1"}],constraints="|s|<=10^4"),
            TaskTemplate(title="Подсчёт символов",domain=TaskDomain.STRINGS,level=DifficultyLevel.JUNIOR,description="Дана строка. Для каждого уникального символа (в алфавитном порядке) выведите символ и количество его вхождений в формате 'символ:число'.",input_format="строка",output_format="символ:число",reference_solution='s=input()\nfor c in sorted(set(s)):print(f\'{c}:{s.count(c)}\')',visible_tests=[{"input": "hello", "expected": "e:1\nh:1\nl:2\no:1"}],hidden_tests=[{"input": "a", "expected": "a:1"}],constraints="|s|<=1000"),
            TaskTemplate(title="Конвертер температуры",domain=TaskDomain.MATH,level=DifficultyLevel.JUNIOR,description="Дана температура в градусах Цельсия (C). Переведите её в градусы Фаренгейта по формуле F = C × 9/5 + 32. Выведите результат с одним знаком после запятой.",input_format="C",output_format="F",reference_solution='c=float(input())\nprint(round(c*9/5+32,1))',visible_tests=[{"input": "100", "expected": "212.0"}],hidden_tests=[{"input": "0", "expected": "32.0"}],constraints="C<=1000"),
            TaskTemplate(title="Класс Прямоугольник",domain=TaskDomain.OOP,level=DifficultyLevel.JUNIOR,description="Даны ширина и высота прямоугольника. Вычислите и выведите через пробел его площадь (w×h) и периметр (2×(w+h)).",input_format="w h",output_format="area perimeter",reference_solution='w,h=map(int,input().split())\nprint(w*h,2*(w+h))',visible_tests=[{"input": "3 4", "expected": "12 14"}],hidden_tests=[{"input": "1 1", "expected": "1 4"}],constraints="w,h<=1000"),
            TaskTemplate(title="Два числа с суммой",domain=TaskDomain.HASH_TABLES,level=DifficultyLevel.MIDDLE,description="Дан массив из n целых чисел и целевое число target. Найдите два элемента, сумма которых равна target, и выведите их индексы (нумерация с 0).",input_format="n target, массив",output_format="индексы",reference_solution='l=input().split()\nn,t=int(l[0]),int(l[1])\na=list(map(int,input().split()))\nd={}\nfor i,x in enumerate(a):\n if t-x in d:print(d[t-x],i);break\n d[x]=i',visible_tests=[{"input": "4 9\n2 7 11 15", "expected": "0 1"}],hidden_tests=[{"input": "2 3\n1 2", "expected": "0 1"}],constraints="n<=10^5"),
            TaskTemplate(title="Бинарный поиск",domain=TaskDomain.ARRAYS,level=DifficultyLevel.MIDDLE,description="Дан отсортированный массив из n чисел и число x. Найдите индекс элемента x в массиве с помощью бинарного поиска. Если элемент не найден, выведите -1.",input_format="n x, массив",output_format="индекс",reference_solution='n,x=map(int,input().split())\na=list(map(int,input().split()))\nlo,hi=0,n-1;r=-1\nwhile lo<=hi:\n m=(lo+hi)//2\n if a[m]==x:r=m;break\n elif a[m]<x:lo=m+1\n else:hi=m-1\nprint(r)',visible_tests=[{"input": "5 3\n1 2 3 4 5", "expected": "2"}],hidden_tests=[{"input": "1 1\n1", "expected": "0"}],constraints="n<=10^6"),
            TaskTemplate(title="BFS кратчайший путь",domain=TaskDomain.GRAPHS,level=DifficultyLevel.MIDDLE,description="Дан невзвешенный граф из n вершин и m рёбер. Найдите длину кратчайшего пути от вершины 1 до вершины n с помощью BFS. Если пути нет, выведите -1.",input_format="n m, рёбра",output_format="расстояние",reference_solution='from collections import deque\nn,m=map(int,input().split())\ng=[[]for _ in range(n+1)]\nfor _ in range(m):u,v=map(int,input().split());g[u].append(v);g[v].append(u)\nd=[-1]*(n+1);d[1]=0;q=deque([1])\nwhile q:\n u=q.popleft()\n for v in g[u]:\n  if d[v]==-1:d[v]=d[u]+1;q.append(v)\nprint(d[n])',visible_tests=[{"input": "4 4\n1 2\n2 3\n3 4\n1 3", "expected": "2"}],hidden_tests=[{"input": "2 0", "expected": "-1"}],constraints="n<=10^5"),
            TaskTemplate(title="Лестница DP",domain=TaskDomain.DYNAMIC_PROGRAMMING,level=DifficultyLevel.MIDDLE,description="За один шаг можно подняться на 1 или 2 ступеньки. Сколько различных способов подняться на n-ю ступеньку? Используйте динамическое программирование.",input_format="n",output_format="количество",reference_solution='n=int(input())\nif n<=2:print(n)\nelse:\n a,b=1,2\n for _ in range(3,n+1):a,b=b,a+b\n print(b)',visible_tests=[{"input": "5", "expected": "8"}],hidden_tests=[{"input": "1", "expected": "1"}],constraints="n<=45"),
            TaskTemplate(title="Анаграммы",domain=TaskDomain.STRINGS,level=DifficultyLevel.MIDDLE,description="Даны две строки (каждая на отдельной строке). Определите, являются ли они анаграммами (содержат одинаковые буквы в разном порядке). Выведите YES или NO.",input_format="две строки",output_format="YES/NO",reference_solution='print(\'YES\' if sorted(input().lower())==sorted(input().lower()) else \'NO\')',visible_tests=[{"input": "listen\nsilent", "expected": "YES"}],hidden_tests=[{"input": "ab\ncd", "expected": "NO"}],constraints="|s|<=10^5"),
            TaskTemplate(title="Поворот матрицы",domain=TaskDomain.ARRAYS,level=DifficultyLevel.MIDDLE,description="Дана квадратная матрица NxN. Поверните её на 90 градусов по часовой стрелке и выведите результат. Каждый ряд — на отдельной строке, числа через пробел.",input_format="n, матрица",output_format="матрица",reference_solution='n=int(input())\nm=[list(map(int,input().split()))for _ in range(n)]\nfor i in range(n):print(*[m[n-1-j][i]for j in range(n)])',visible_tests=[{"input": "3\n1 2 3\n4 5 6\n7 8 9", "expected": "7 4 1\n8 5 2\n9 6 3"}],hidden_tests=[{"input": "2\n1 2\n3 4", "expected": "3 1\n4 2"}],constraints="n<=100"),
            TaskTemplate(title="REST API запрос",domain=TaskDomain.API,level=DifficultyLevel.MIDDLE,description="Напишите Python-код, который выполняет GET-запрос к URL (передаётся через input()) с помощью библиотеки requests и выводит полученные данные в формате JSON. Используйте requests.get() и метод .json().",input_format="URL",output_format="Python код",reference_solution='import requests\nprint(requests.get(input()).json())',visible_tests=[{"input": "example", "expected": "import requests\nresponse = requests.get(url)\nprint(response.json())"}],hidden_tests=[{"input": "check", "expected": "requests.get"}],constraints="Python"),
            TaskTemplate(title="Стек с min O(1)",domain=TaskDomain.OOP,level=DifficultyLevel.MIDDLE,description="Реализуйте стек с операциями push, pop и min, где min возвращает минимальный элемент за O(1). На вход подаётся n команд. Для команды min выведите текущий минимум.",input_format="команды",output_format="min",reference_solution='n=int(input())\nst=[];mn=[]\nfor _ in range(n):\n c=input().split()\n if c[0]==\'push\':v=int(c[1]);st.append(v);mn.append(min(v,mn[-1]) if mn else v)\n elif c[0]==\'pop\':st.pop();mn.pop()\n elif c[0]==\'min\':print(mn[-1])',visible_tests=[{"input": "5\npush 3\npush 1\nmin\npop\nmin", "expected": "1\n3"}],hidden_tests=[{"input": "2\npush 5\nmin", "expected": "5"}],constraints="n<=10^5"),
            TaskTemplate(title="НОП LCS",domain=TaskDomain.DYNAMIC_PROGRAMMING,level=DifficultyLevel.SENIOR,description="Даны две строки. Найдите длину их наибольшей общей подпоследовательности (LCS) с помощью динамического программирования.",input_format="две строки",output_format="длина",reference_solution='s1=input();s2=input()\nm,n=len(s1),len(s2)\ndp=[[0]*(n+1)for _ in range(m+1)]\nfor i in range(1,m+1):\n for j in range(1,n+1):dp[i][j]=dp[i-1][j-1]+1 if s1[i-1]==s2[j-1] else max(dp[i-1][j],dp[i][j-1])\nprint(dp[m][n])',visible_tests=[{"input": "abcde\nace", "expected": "3"}],hidden_tests=[{"input": "abc\ndef", "expected": "0"}],constraints="|s|<=1000"),
            TaskTemplate(title="Рюкзак 0/1",domain=TaskDomain.DYNAMIC_PROGRAMMING,level=DifficultyLevel.SENIOR,description="Задача о рюкзаке 0/1: дано n предметов (вес и стоимость каждого) и максимальная вместимость W. Найдите максимальную суммарную стоимость, которую можно поместить в рюкзак.",input_format="n W, пары",output_format="макс",reference_solution='n,W=map(int,input().split())\nitems=[tuple(map(int,input().split()))for _ in range(n)]\ndp=[0]*(W+1)\nfor w,v in items:\n for j in range(W,w-1,-1):dp[j]=max(dp[j],dp[j-w]+v)\nprint(dp[W])',visible_tests=[{"input": "3 50\n10 60\n20 100\n30 120", "expected": "220"}],hidden_tests=[{"input": "1 1\n2 3", "expected": "0"}],constraints="n<=100"),
            TaskTemplate(title="Дейкстра",domain=TaskDomain.GRAPHS,level=DifficultyLevel.SENIOR,description="Дан взвешенный граф из n вершин и m рёбер. Найдите кратчайшие расстояния от вершины 1 до всех остальных с помощью алгоритма Дейкстры. Если вершина недостижима, выведите -1.",input_format="n m, рёбра",output_format="расстояния",reference_solution='import heapq\nn,m=map(int,input().split())\ng=[[]for _ in range(n+1)]\nfor _ in range(m):u,v,w=map(int,input().split());g[u].append((v,w));g[v].append((u,w))\nd=[10**18]*(n+1);d[1]=0;pq=[(0,1)]\nwhile pq:\n du,u=heapq.heappop(pq)\n if du>d[u]:continue\n for v,w in g[u]:\n  if d[u]+w<d[v]:d[v]=d[u]+w;heapq.heappush(pq,(d[v],v))\nprint(*[x if x<10**18 else -1 for x in d[1:]])',visible_tests=[{"input": "3 3\n1 2 1\n2 3 2\n1 3 4", "expected": "0 1 3"}],hidden_tests=[{"input": "2 0", "expected": "0 -1"}],constraints="n<=10^5"),
            TaskTemplate(title="Декоратор cache",domain=TaskDomain.OOP,level=DifficultyLevel.SENIOR,description="Напишите декоратор cache, который запоминает результаты вызова функции (мемоизация). Примените его к функции вычисления n-го числа Фибоначчи и выведите результат для заданного n.",input_format="n",output_format="fib(n)",reference_solution='def cache(f):\n m={}\n def w(*a):\n  if a not in m:m[a]=f(*a)\n  return m[a]\n return w\n@cache\ndef fib(n):return n if n<2 else fib(n-1)+fib(n-2)\nprint(fib(int(input())))',visible_tests=[{"input": "10", "expected": "55"}],hidden_tests=[{"input": "0", "expected": "0"}],constraints="n<=40"),
            TaskTemplate(title="Trie дерево",domain=TaskDomain.TREES,level=DifficultyLevel.SENIOR,description="Реализуйте структуру данных Trie (префиксное дерево) с операциями insert (добавить слово) и search (найти слово). На вход подаётся n команд: 'i слово' или 's слово'. Для search выведите YES или NO.",input_format="команды",output_format="YES/NO",reference_solution='class N:\n def __init__(self):self.c={};self.e=False\nt=N()\ndef ins(w):\n n=t\n for c in w:n.c.setdefault(c,N());n=n.c[c]\n n.e=True\ndef src(w):\n n=t\n for c in w:\n  if c not in n.c:return False\n  n=n.c[c]\n return n.e\nfor _ in range(int(input())):\n p=input().split()\n if p[0]==\'i\':ins(p[1])\n else:print(\'YES\' if src(p[1]) else \'NO\')',visible_tests=[{"input": "3\ni app\ns app\ns ap", "expected": "YES\nNO"}],hidden_tests=[{"input": "2\ni hi\ns hi", "expected": "YES"}],constraints="n<=10^4"),
            TaskTemplate(title="SQL: средняя зарплата по отделам",domain=TaskDomain.SQL,level=DifficultyLevel.JUNIOR,description="Напишите SQL-запрос, который вычисляет среднюю зарплату сотрудников в каждом отделе. Таблица emp содержит столбцы: id, name, dept (отдел), salary. Результат должен содержать название отдела и среднюю зарплату.",input_format="SQL",output_format="dept,avg",reference_solution='SELECT dept,AVG(salary) FROM emp GROUP BY dept',visible_tests=[{"input": "example", "expected": "Подсказка: используйте AVG() и GROUP BY по столбцу dept"}],hidden_tests=[{"input": "check", "expected": "GROUP BY"}],constraints="SQL"),
            TaskTemplate(title="SQL: JOIN сотрудников и отделов",domain=TaskDomain.SQL,level=DifficultyLevel.JUNIOR,description="Напишите SQL-запрос, который выводит имена всех сотрудников вместе с названиями их отделов. Используйте LEFT JOIN, чтобы включить сотрудников без отдела. Таблицы: emp(id, name, did), dept(id, name).",input_format="SQL",output_format="result",reference_solution='SELECT e.name,d.name FROM emp e LEFT JOIN dept d ON e.did=d.id',visible_tests=[{"input": "example", "expected": "Подсказка: используйте LEFT JOIN для объединения таблиц emp и dept"}],hidden_tests=[{"input": "check", "expected": "JOIN"}],constraints="SQL"),
            TaskTemplate(title="SQL: топ-3 активных клиента",domain=TaskDomain.SQL,level=DifficultyLevel.MIDDLE,description="Напишите SQL-запрос, который находит трёх клиентов с наибольшим количеством заказов. Таблица orders содержит: id, name, created_at. Результат: имя клиента и количество заказов, отсортированные по убыванию.",input_format="SQL",output_format="name,cnt",reference_solution='SELECT name,COUNT(*) c FROM orders GROUP BY name ORDER BY c DESC LIMIT 3',visible_tests=[{"input": "example", "expected": "Подсказка: используйте COUNT(*), GROUP BY, ORDER BY DESC и LIMIT 3"}],hidden_tests=[{"input": "check", "expected": "COUNT"}],constraints="SQL"),
            TaskTemplate(title="SQL: зарплата выше средней",domain=TaskDomain.SQL,level=DifficultyLevel.MIDDLE,description="Напишите SQL-запрос с подзапросом, который выводит имена сотрудников, чья зарплата выше средней по компании. Таблица emp: id, name, salary.",input_format="SQL",output_format="result",reference_solution='SELECT name FROM emp WHERE salary>(SELECT AVG(salary) FROM emp)',visible_tests=[{"input": "example", "expected": "Подсказка: используйте подзапрос с AVG(salary) в условии WHERE"}],hidden_tests=[{"input": "check", "expected": "AVG"}],constraints="SQL"),
            TaskTemplate(title="SQL: ранжирование зарплат по отделам",domain=TaskDomain.SQL,level=DifficultyLevel.SENIOR,description="Напишите SQL-запрос с оконной функцией RANK(), который присваивает ранг каждому сотруднику внутри его отдела по убыванию зарплаты. Таблица emp: id, name, dept, salary. Результат: имя, ранг.",input_format="SQL",output_format="result",reference_solution='SELECT name,RANK() OVER(PARTITION BY dept ORDER BY salary DESC) FROM emp',visible_tests=[{"input": "example", "expected": "Подсказка: используйте RANK() OVER (PARTITION BY ... ORDER BY ...)"}],hidden_tests=[{"input": "check", "expected": "PARTITION"}],constraints="SQL"),
            TaskTemplate(title="Pandas: загрузка и просмотр данных",domain=TaskDomain.PANDAS,level=DifficultyLevel.JUNIOR,description="Напишите Python-код, который загружает CSV-файл (путь передаётся через input()) с помощью pandas и выводит первые 5 строк. Используйте pd.read_csv() и метод .head().",input_format="файл",output_format="код",reference_solution='import pandas as pd\nprint(pd.read_csv(input()).head())',visible_tests=[{"input": "example", "expected": "Подсказка: pd.read_csv() для загрузки, .head() для первых строк"}],hidden_tests=[{"input": "check", "expected": "read_csv"}],constraints="pandas"),
            TaskTemplate(title="Pandas: средняя зарплата по городам",domain=TaskDomain.PANDAS,level=DifficultyLevel.MIDDLE,description="Напишите Python-код, который загружает CSV-файл d.csv и вычисляет среднюю зарплату (столбец salary) по каждому городу (столбец city). Используйте groupby() и mean().",input_format="описание",output_format="код",reference_solution='import pandas as pd\nprint(pd.read_csv(\'d.csv\').groupby(\'city\')[\'salary\'].mean())',visible_tests=[{"input": "example", "expected": "Подсказка: используйте df.groupby(city)[salary].mean()"}],hidden_tests=[{"input": "check", "expected": "groupby"}],constraints="pandas"),
            TaskTemplate(title="Pandas: фильтрация и сортировка",domain=TaskDomain.PANDAS,level=DifficultyLevel.MIDDLE,description="Напишите Python-код, который из файла d.csv отбирает сотрудников старше 30 лет (столбец age) и сортирует их по зарплате (столбец salary) по убыванию. Используйте DataFrame-фильтрацию и sort_values().",input_format="описание",output_format="код",reference_solution='import pandas as pd\ndf=pd.read_csv(\'d.csv\')\nprint(df[df[\'age\']>30].sort_values(\'salary\',ascending=False))',visible_tests=[{"input": "example", "expected": "Подсказка: фильтрация df[условие] и .sort_values(ascending=False)"}],hidden_tests=[{"input": "check", "expected": "sort_values"}],constraints="pandas"),
            TaskTemplate(title="Pandas: сводная таблица продаж",domain=TaskDomain.PANDAS,level=DifficultyLevel.SENIOR,description="Напишите Python-код, который из файла s.csv строит сводную таблицу: строки — отделы (dept), столбцы — кварталы (q), значения — сумма продаж (amt). Используйте pd.pivot_table() с aggfunc=sum.",input_format="описание",output_format="код",reference_solution='import pandas as pd\nprint(pd.pivot_table(pd.read_csv(\'s.csv\'),values=\'amt\',index=\'dept\',columns=\'q\',aggfunc=\'sum\'))',visible_tests=[{"input": "example", "expected": "Подсказка: pd.pivot_table() с параметрами values, index, columns, aggfunc"}],hidden_tests=[{"input": "check", "expected": "pivot_table"}],constraints="pandas"),
            TaskTemplate(title="Расчёт воронки конверсии",domain=TaskDomain.METRICS,level=DifficultyLevel.MIDDLE,description="Напишите программу, которая рассчитывает процент конверсии на каждом этапе воронки продаж. На вход подаётся количество этапов и для каждого — название и количество пользователей. Выведите процент от первого этапа для каждого шага.",input_format="этапы",output_format="конверсия",reference_solution='n=int(input())\ns=[input().split() for _ in range(n)]\nfor i,p in enumerate(s):print(f\'{p[0]}: {int(p[1])*100//int(s[0][1])}%\')',visible_tests=[{"input": "3\nvisits 1000\ncart 200\nbuy 50", "expected": "visits: 100%\ncart: 20%\nbuy: 5%"}],hidden_tests=[{"input": "1\na 100", "expected": "a: 100%"}],constraints="n<=10"),
            TaskTemplate(title="Linux: поиск больших файлов",domain=TaskDomain.LINUX,level=DifficultyLevel.JUNIOR,description="Напишите bash-команду, которая находит все файлы в директории /var/log размером более 100 МБ. Используйте команду find с параметром -size.",input_format="bash",output_format="команда",reference_solution='Подсказка: find <путь> -size +100M',visible_tests=[{"input": "example", "expected": "Подсказка: find <путь> -size +100M"}],hidden_tests=[{"input": "check", "expected": "find"}],constraints="Bash"),
            TaskTemplate(title="Bash: подсчёт строк в файле",domain=TaskDomain.BASH,level=DifficultyLevel.JUNIOR,description="Напишите bash-команду, которая подсчитывает количество строк в файле file.txt. Используйте утилиту wc с флагом -l.",input_format="bash",output_format="команда",reference_solution='Подсказка: wc -l < файл',visible_tests=[{"input": "example", "expected": "Подсказка: wc -l < файл"}],hidden_tests=[{"input": "check", "expected": "wc"}],constraints="Bash"),
            TaskTemplate(title="Bash log rotation",domain=TaskDomain.BASH,level=DifficultyLevel.JUNIOR,description="Напишите bash-команду, которая находит все файлы .log в /var/log старше 7 дней и сжимает их с помощью gzip. Используйте find с параметром -mtime.",input_format="bash",output_format="скрипт",reference_solution='find /var/log -name \'*.log\' -mtime +7 -exec gzip {} \\;',visible_tests=[{"input": "example", "expected": "Подсказка: find -name -mtime +7 -exec gzip"}],hidden_tests=[{"input": "check", "expected": "mtime"}],constraints="Bash"),
            TaskTemplate(title="Dockerfile для Flask-приложения",domain=TaskDomain.DOCKER,level=DifficultyLevel.JUNIOR,description="Напишите Dockerfile для контейнеризации Flask-приложения. Базовый образ — python:3.11-slim. Скопируйте файлы проекта, установите зависимости из requirements.txt и запустите app.py.",input_format="Dockerfile",output_format="файл",reference_solution='FROM python:3.11-slim\nWORKDIR /app\nCOPY . .\nRUN pip install -r requirements.txt\nCMD [\'python\',\'app.py\']',visible_tests=[{"input": "example", "expected": "Подсказка: FROM -> WORKDIR -> COPY -> RUN pip install -> CMD"}],hidden_tests=[{"input": "check", "expected": "FROM"}],constraints="Docker"),
            TaskTemplate(title="Docker Compose: Flask + PostgreSQL",domain=TaskDomain.DOCKER,level=DifficultyLevel.MIDDLE,description="Напишите docker-compose.yml, который поднимает два сервиса: web (Flask-приложение, build из текущей папки, порт 5000) и db (PostgreSQL 15). Опишите связь между сервисами.",input_format="YAML",output_format="compose",reference_solution='version: \'3\'\nservices:\n  web:\n    build: .\n    ports: [\'5000:5000\']\n  db:\n    image: postgres:15',visible_tests=[{"input": "example", "expected": "Подсказка: секция services с build/image, ports, depends_on"}],hidden_tests=[{"input": "check", "expected": "services"}],constraints="Docker Compose"),
            TaskTemplate(title="K8s Deployment",domain=TaskDomain.YAML_CONFIG,level=DifficultyLevel.MIDDLE,description="Напишите YAML-манифест Kubernetes Deployment для развёртывания nginx в 3 репликах. Укажите apiVersion, kind, spec с replicas, template и containers.",input_format="YAML",output_format="yaml",reference_solution='apiVersion: apps/v1\nkind: Deployment\nspec:\n  replicas: 3',visible_tests=[{"input": "example", "expected": "Подсказка: apiVersion: apps/v1, kind: Deployment, spec.replicas: 3, containers"}],hidden_tests=[{"input": "check", "expected": "replicas"}],constraints="K8s"),
            TaskTemplate(title="GitHub Actions",domain=TaskDomain.CI_CD,level=DifficultyLevel.MIDDLE,description="Напишите GitHub Actions workflow (YAML), который запускает pytest при каждом push. Используйте ubuntu-latest, actions/checkout и команду pip install + pytest.",input_format="YAML",output_format="workflow",reference_solution='name: CI\non: push\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v3\n      - run: pytest',visible_tests=[{"input": "example", "expected": "Подсказка: on: push, jobs.test.runs-on: ubuntu-latest, steps с checkout, pip install, pytest"}],hidden_tests=[{"input": "check", "expected": "pytest"}],constraints="CI/CD"),
            TaskTemplate(title="Dockerfile: multi-stage сборка",domain=TaskDomain.DOCKER,level=DifficultyLevel.SENIOR,description="Напишите Dockerfile с multi-stage сборкой для Python-приложения. Первый этап (AS build) — установка зависимостей, второй — копирование только необходимых файлов в slim-образ для уменьшения размера.",input_format="Dockerfile",output_format="файл",reference_solution='FROM python:3.11 AS build\nRUN pip install --user -r req.txt\nFROM python:3.11-slim\nCOPY --from=build /root/.local /root/.local',visible_tests=[{"input": "example", "expected": "Подсказка: два этапа FROM ... AS build и COPY --from=build"}],hidden_tests=[{"input": "check", "expected": "AS build"}],constraints="Docker"),
            TaskTemplate(title="Bash мониторинг",domain=TaskDomain.BASH,level=DifficultyLevel.MIDDLE,description="Напишите bash-скрипт мониторинга, который проверяет загрузку CPU. Если загрузка выше 80%, выводит ALERT. Используйте команду top для получения данных.",input_format="bash",output_format="скрипт",reference_solution='#!/bin/bash\nCPU=$(top -bn1|grep Cpu|awk \'{print $2}\')\n[ $(echo "$CPU>80"|bc) -eq 1 ] && echo ALERT',visible_tests=[{"input": "example", "expected": "#!/bin/bash\nCPU=$(top -bn1 | grep Cpu | awk {print $2})\nif [ $(echo \"$CPU>80\" | bc) -eq 1 ]; then echo ALERT; fi"}],hidden_tests=[{"input": "check", "expected": "top"}],constraints="Bash"),
            TaskTemplate(title="Nginx proxy",domain=TaskDomain.YAML_CONFIG,level=DifficultyLevel.MIDDLE,description="Напишите конфигурацию Nginx для reverse proxy. Сервер слушает порт 80 и перенаправляет все запросы на http://localhost:3000. Используйте директиву proxy_pass.",input_format="конфиг",output_format="nginx",reference_solution='Подсказка: server { listen 80; location / { proxy_pass ... } }',visible_tests=[{"input": "example", "expected": "Подсказка: server { listen 80; location / { proxy_pass ... } }"}],hidden_tests=[{"input": "check", "expected": "proxy_pass"}],constraints="Nginx"),
            TaskTemplate(title="Базовые тесты с pytest",domain=TaskDomain.PYTEST,level=DifficultyLevel.JUNIOR,description="Напишите функцию add(a, b), которая возвращает сумму двух чисел, и тест test_add(), проверяющий её работу с помощью pytest. Используйте assert для проверки результата.",input_format="Python",output_format="тест",reference_solution='def test_add(): assert 2+3==5',visible_tests=[{"input": "example", "expected": "Подсказка: def функция + def test_функция с assert"}],hidden_tests=[{"input": "check", "expected": "assert"}],constraints="pytest"),
            TaskTemplate(title="Тест-кейсы формы регистрации",domain=TaskDomain.TESTING,level=DifficultyLevel.JUNIOR,description="Напишите набор тест-кейсов для проверки формы регистрации. Форма содержит поля: email, пароль, подтверждение пароля. Опишите позитивные и негативные сценарии: корректные данные, пустые поля, невалидный email, короткий пароль, несовпадающие пароли.",input_format="описание",output_format="кейсы",reference_solution='TC1:Valid->OK TC2:Empty->Err TC3:BadEmail->Err TC4:ShortPwd->Err',visible_tests=[{"input": "example", "expected": "Подсказка: TC1-позитивный, TC2-пустые поля, TC3-невалидные, TC4-граничные"}],hidden_tests=[{"input": "check", "expected": "TC"}],constraints="QA"),
            TaskTemplate(title="pytest: параметризованные тесты",domain=TaskDomain.PYTEST,level=DifficultyLevel.MIDDLE,description="Напишите параметризованный pytest-тест с @pytest.mark.parametrize для функции multiply(a, b). Проверьте минимум 4 набора входных данных: положительные, отрицательные числа, ноль, дробные.",input_format="Python",output_format="тест",reference_solution='import pytest\n@pytest.mark.parametrize(\'a,b,r\',[(2,3,5),(0,0,0)])\ndef test(a,b,r):assert a+b==r',visible_tests=[{"input": "c", "expected": "parametrize"}],hidden_tests=[{"input": "c2", "expected": "mark"}],constraints="pytest"),
            TaskTemplate(title="pytest: фикстура подключения к БД",domain=TaskDomain.PYTEST,level=DifficultyLevel.MIDDLE,description="Напишите pytest-фикстуру @pytest.fixture, которая создаёт подключение к тестовой SQLite базе данных, передаёт его в тест, а после теста закрывает соединение (yield). Используйте sqlite3.connect().",input_format="Python",output_format="conftest",reference_solution='import pytest\n@pytest.fixture\ndef db():\n d={}\n yield d\n d.clear()',visible_tests=[{"input": "c", "expected": "fixture"}],hidden_tests=[{"input": "c2", "expected": "yield"}],constraints="pytest"),
            TaskTemplate(title="Selenium: тест формы логина",domain=TaskDomain.SELENIUM,level=DifficultyLevel.MIDDLE,description="Напишите Selenium-тест, который открывает страницу логина, вводит email (test@example.com) и пароль (pass123) в соответствующие поля, нажимает кнопку входа и проверяет, что произошёл редирект на страницу /dashboard.",input_format="Python",output_format="тест",reference_solution='from selenium.webdriver.common.by import By\nd.find_element(By.ID,\'email\').send_keys(\'t@t.com\')',visible_tests=[{"input": "c", "expected": "selenium"}],hidden_tests=[{"input": "c2", "expected": "find_element"}],constraints="Selenium"),
            TaskTemplate(title="Поиск бага",domain=TaskDomain.TESTING,level=DifficultyLevel.MIDDLE,description="Функция divide(a, b) должна возвращать a/b, но падает при b=0. Напишите исправленную версию, которая при b=0 возвращает 'Ошибка', а при корректных данных — результат с точностью до 2 знаков.",input_format="код",output_format="исправление",reference_solution='def safe_div(a,b):\n if b==0: raise ValueError\n return a/b',visible_tests=[{"input": "div(1,0)", "expected": "error"}],hidden_tests=[{"input": "c", "expected": "b==0"}],constraints="Python"),
            TaskTemplate(title="pytest: мокирование HTTP-запросов",domain=TaskDomain.PYTEST,level=DifficultyLevel.SENIOR,description="Напишите pytest-тест с использованием unittest.mock.patch для мокирования requests.get(). Функция fetch_user(user_id) выполняет GET-запрос к https://api.example.com/users/{id}. Замокайте ответ с JSON {id: 1, name: Test} и проверьте, что функция корректно парсит результат.",input_format="Python",output_format="тест",reference_solution='from unittest.mock import patch\n@patch(\'requests.get\')\ndef test(m):m.return_value.json.return_value={\'ok\':1}',visible_tests=[{"input": "c", "expected": "patch"}],hidden_tests=[{"input": "c2", "expected": "mock"}],constraints="pytest"),
            TaskTemplate(title="Selenium: Page Object Model",domain=TaskDomain.SELENIUM,level=DifficultyLevel.SENIOR,description="Реализуйте паттерн Page Object Model для страницы логина. Создайте класс LoginPage с атрибутами: URL, локаторы полей email/password/submit, методы enter_email(), enter_password(), click_submit(), login(email, password). Напишите тест, использующий этот Page Object.",input_format="Python",output_format="класс",reference_solution='class LoginPage:\n def __init__(s,d):s.d=d\n def login(s,e,p):s.d.find_element(\'id\',\'email\').send_keys(e)',visible_tests=[{"input": "c", "expected": "Page"}],hidden_tests=[{"input": "c2", "expected": "class"}],constraints="Selenium"),
            TaskTemplate(title="sklearn: линейная регрессия",domain=TaskDomain.SKLEARN,level=DifficultyLevel.JUNIOR,description="Напишите Python-код, который обучает модель линейной регрессии (LinearRegression) на данных X, y, делает предсказание для нового значения и выводит коэффициенты модели (coef_, intercept_). Используйте sklearn.linear_model.",input_format="Python",output_format="код",reference_solution='from sklearn.linear_model import LinearRegression\nLinearRegression().fit([[1],[2]],[2,4]).predict([[3]])',visible_tests=[{"input": "c", "expected": "LinearRegression"}],hidden_tests=[{"input": "c2", "expected": "fit"}],constraints="sklearn"),
            TaskTemplate(title="Нормализация данных Min-Max",domain=TaskDomain.DATA_PROCESSING,level=DifficultyLevel.JUNIOR,description="Дан массив из n чисел. Нормализуйте его в диапазон [0, 1] по формуле: x_norm = (x - min) / (max - min). Выведите нормализованные значения, округлённые до 2 знаков.",input_format="n, массив",output_format="результат",reference_solution='n=int(input())\na=list(map(float,input().split()))\nmn,mx=min(a),max(a)\nprint(*[round((x-mn)/(mx-mn),2)for x in a])',visible_tests=[{"input": "5\n1 2 3 4 5", "expected": "0.0 0.25 0.5 0.75 1.0"}],hidden_tests=[{"input": "2\n0 10", "expected": "0.0 1.0"}],constraints="n<=10^5"),
            TaskTemplate(title="Обработка пропусков",domain=TaskDomain.DATA_PROCESSING,level=DifficultyLevel.JUNIOR,description="Напишите Python-код, который загружает CSV с пропусками. Для числовых столбцов замените NaN средним значением (fillna + mean). Выведите количество оставшихся пропусков.",input_format="pandas",output_format="код",reference_solution='import pandas as pd,numpy as np\ndf=pd.DataFrame({\'a\':[1,np.nan,3]})\ndf[\'a\']=df[\'a\'].fillna(df[\'a\'].mean())',visible_tests=[{"input": "c", "expected": "fillna"}],hidden_tests=[{"input": "c2", "expected": "mean"}],constraints="pandas"),
            TaskTemplate(title="sklearn: Random Forest на Iris",domain=TaskDomain.SKLEARN,level=DifficultyLevel.MIDDLE,description="Напишите Python-код, который загружает датасет Iris (sklearn.datasets.load_iris), обучает RandomForestClassifier с n_estimators=100, оценивает точность на тестовой выборке (test_size=0.2, random_state=42) и выводит accuracy.",input_format="Python",output_format="код",reference_solution='from sklearn.ensemble import RandomForestClassifier\nRandomForestClassifier().fit(X_train,y_train)',visible_tests=[{"input": "c", "expected": "RandomForest"}],hidden_tests=[{"input": "c2", "expected": "fit"}],constraints="sklearn"),
            TaskTemplate(title="sklearn: 5-fold кросс-валидация",domain=TaskDomain.SKLEARN,level=DifficultyLevel.MIDDLE,description="Напишите Python-код, который выполняет 5-фолдовую кросс-валидацию модели SVC() на данных X, y с помощью cross_val_score(). Выведите массив точностей по каждому фолду и среднее значение accuracy.",input_format="Python",output_format="код",reference_solution='from sklearn.model_selection import cross_val_score\ncross_val_score(SVC(),X,y,cv=5).mean()',visible_tests=[{"input": "c", "expected": "cross_val"}],hidden_tests=[{"input": "c2", "expected": "cv=5"}],constraints="sklearn"),
            TaskTemplate(title="Метрики классификации (Precision, Recall, F1)",domain=TaskDomain.METRICS,level=DifficultyLevel.MIDDLE,description="Даны четыре числа: TP (true positives), FP (false positives), FN (false negatives), TN (true negatives). Вычислите Precision = TP/(TP+FP), Recall = TP/(TP+FN), F1 = 2·P·R/(P+R). Выведите три числа, округлённые до 2 знаков.",input_format="TP FP FN TN",output_format="метрики",reference_solution='tp,fp,fn,tn=map(int,input().split())\np=tp/(tp+fp) if tp+fp else 0\nr=tp/(tp+fn) if tp+fn else 0\nf=2*p*r/(p+r) if p+r else 0\nprint(f"{p:.2f} {r:.2f} {f:.2f}")',visible_tests=[{"input": "50 10 5 100", "expected": "0.83 0.91 0.87"}],hidden_tests=[{"input": "0 0 0 0", "expected": "0.0 0.0 0.0"}],constraints="ML"),
            TaskTemplate(title="Feature Engineering из datetime",domain=TaskDomain.DATA_PROCESSING,level=DifficultyLevel.SENIOR,description="Напишите Python-код, который из столбца date (формат datetime) DataFrame создаёт новые признаки: year, month, day_of_week, is_weekend, quarter. Используйте .dt accessor pandas.",input_format="pandas",output_format="код",reference_solution='df[\'year\']=df[\'date\'].dt.year\ndf[\'dow\']=df[\'date\'].dt.dayofweek',visible_tests=[{"input": "c", "expected": "dt.year"}],hidden_tests=[{"input": "c2", "expected": "dayofweek"}],constraints="pandas"),
            TaskTemplate(title="sklearn: Pipeline обработки данных",domain=TaskDomain.SKLEARN,level=DifficultyLevel.SENIOR,description="Напишите Python-код, который создаёт Pipeline из трёх шагов: StandardScaler (нормализация), PCA (снижение размерности до 2 компонент), LogisticRegression (классификация). Обучите Pipeline на данных X, y и выведите точность.",input_format="Python",output_format="код",reference_solution='from sklearn.pipeline import Pipeline\nPipeline([("s",StandardScaler()),("p",PCA()),("lr",LogisticRegression())]).fit(X,y)',visible_tests=[{"input": "example", "expected": "from sklearn.pipeline import Pipeline\nPipeline([(scaler, StandardScaler()), (pca, PCA()), (lr, LogisticRegression())])"}],hidden_tests=[{"input": "check", "expected": "Pipeline"}],constraints="sklearn"),
        # ─── ДОПОЛНИТЕЛЬНЫЕ ЗАДАЧИ (расширение до 100+) ───

        # === РАЗРАБОТКА: дополнительные алгоритмы ===
        TaskTemplate(title="Числа Фибоначчи (итеративно)",domain=TaskDomain.MATH,level=DifficultyLevel.JUNIOR,description="Дано число n. Выведите n-е число Фибоначчи. F(0)=0, F(1)=1, F(n)=F(n-1)+F(n-2).",input_format="n",output_format="F(n)",visible_tests=[{"input":"6","expected":"8"}],hidden_tests=[{"input":"10","expected":"55"},{"input":"0","expected":"0"}],reference_solution="n=int(input())\na,b=0,1\nfor _ in range(n):\n    a,b=b,a+b\nprint(a)"),
        TaskTemplate(title="Удаление дубликатов из массива",domain=TaskDomain.ARRAYS,level=DifficultyLevel.JUNIOR,description="Дан массив из n целых чисел. Выведите массив без дубликатов, сохраняя порядок первого появления элементов.",input_format="n\na1 a2 ... an",output_format="уникальные элементы",visible_tests=[{"input":"7\n1 2 3 2 1 4 3","expected":"1 2 3 4"}],hidden_tests=[{"input":"5\n5 5 5 5 5","expected":"5"}],reference_solution="n=int(input())\na=list(map(int,input().split()))\nseen=set()\nr=[]\nfor x in a:\n    if x not in seen:\n        seen.add(x);r.append(x)\nprint(*r)"),
        TaskTemplate(title="Подсчёт гласных и согласных",domain=TaskDomain.STRINGS,level=DifficultyLevel.JUNIOR,description="Дана строка из латинских букв. Подсчитайте количество гласных и согласных букв. Выведите два числа через пробел.",input_format="строка",output_format="гласные согласные",visible_tests=[{"input":"hello","expected":"2 3"}],hidden_tests=[{"input":"aeiou","expected":"5 0"},{"input":"xyz","expected":"0 3"}],reference_solution="s=input().lower()\nv=sum(1 for c in s if c in 'aeiou')\nprint(v, len(s)-v)"),
        TaskTemplate(title="Транспонирование матрицы",domain=TaskDomain.ARRAYS,level=DifficultyLevel.MIDDLE,description="Дана матрица NxM. Транспонируйте её (замените строки на столбцы). Выведите результат.",input_format="n m\nматрица",output_format="транспонированная матрица",visible_tests=[{"input":"2 3\n1 2 3\n4 5 6","expected":"1 4\n2 5\n3 6"}],hidden_tests=[{"input":"1 3\n7 8 9","expected":"7\n8\n9"}],reference_solution="n,m=map(int,input().split())\na=[list(map(int,input().split())) for _ in range(n)]\nfor j in range(m):\n    print(*[a[i][j] for i in range(n)])"),
        TaskTemplate(title="Скобочная последовательность",domain=TaskDomain.STRINGS,level=DifficultyLevel.MIDDLE,description="Дана строка из скобок (){}[]. Определите, является ли последовательность правильной. Выведите YES или NO.",input_format="строка скобок",output_format="YES/NO",visible_tests=[{"input":"({[]})","expected":"YES"},{"input":"({[}])","expected":"NO"}],hidden_tests=[{"input":"","expected":"YES"},{"input":"(","expected":"NO"}],reference_solution="s=input()\nst=[]\np={'(':')','{':'}','[':']'}\nfor c in s:\n    if c in p:st.append(p[c])\n    elif not st or st.pop()!=c:print('NO');exit()\nprint('YES' if not st else 'NO')"),
        TaskTemplate(title="Объединение отсортированных массивов",domain=TaskDomain.SORTING,level=DifficultyLevel.MIDDLE,description="Даны два отсортированных массива. Объедините их в один отсортированный массив за O(n+m).",input_format="n\nмассив1\nm\nмассив2",output_format="объединённый массив",visible_tests=[{"input":"3\n1 3 5\n3\n2 4 6","expected":"1 2 3 4 5 6"}],hidden_tests=[{"input":"2\n1 1\n2\n1 1","expected":"1 1 1 1"}],reference_solution="n=int(input());a=list(map(int,input().split()))\nm=int(input());b=list(map(int,input().split()))\ni=j=0;r=[]\nwhile i<n and j<m:\n    if a[i]<=b[j]:r.append(a[i]);i+=1\n    else:r.append(b[j]);j+=1\nr+=a[i:]+b[j:]\nprint(*r)"),
        TaskTemplate(title="Реализация связного списка",domain=TaskDomain.OOP,level=DifficultyLevel.SENIOR,description="Реализуйте односвязный список с методами append, prepend, delete(value), display. Входные команды: A val (append), P val (prepend), D val (delete), S (show). Для S выведите элементы через ->.",input_format="n команд",output_format="результаты S",visible_tests=[{"input":"5\nA 1\nA 2\nA 3\nD 2\nS","expected":"1->3"}],hidden_tests=[{"input":"3\nP 5\nA 10\nS","expected":"5->10"}],reference_solution="class N:\n    def __init__(s,v):s.v=v;s.n=None\nclass L:\n    def __init__(s):s.h=None\n    def a(s,v):\n        n=N(v)\n        if not s.h:s.h=n;return\n        c=s.h\n        while c.n:c=c.n\n        c.n=n\n    def p(s,v):n=N(v);n.n=s.h;s.h=n\n    def d(s,v):\n        if s.h and s.h.v==v:s.h=s.h.n;return\n        c=s.h\n        while c and c.n:\n            if c.n.v==v:c.n=c.n.n;return\n            c=c.n\n    def s(s):\n        r=[];c=s.h\n        while c:r.append(str(c.v));c=c.n\n        print('->'.join(r))\nl=L()\nfor _ in range(int(input())):\n    cmd=input().split()\n    if cmd[0]=='A':l.a(int(cmd[1]))\n    elif cmd[0]=='P':l.p(int(cmd[1]))\n    elif cmd[0]=='D':l.d(int(cmd[1]))\n    elif cmd[0]=='S':l.s()"),

        # === АНАЛИТИКА: дополнительные SQL + Pandas ===
        TaskTemplate(title="SQL: количество заказов по месяцам",domain=TaskDomain.SQL,level=DifficultyLevel.JUNIOR,description="Напишите SQL-запрос, который подсчитывает количество заказов по месяцам. Таблица orders(id, product, created_at). Используйте DATE_TRUNC или EXTRACT и GROUP BY.",input_format="SQL",output_format="месяц, количество",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: используйте EXTRACT(MONTH FROM ...) и GROUP BY"}],hidden_tests=[{"input":"check","expected":"GROUP BY"}]),
        TaskTemplate(title="SQL: HAVING — фильтрация групп",domain=TaskDomain.SQL,level=DifficultyLevel.MIDDLE,description="Напишите SQL-запрос, который находит отделы с суммарной зарплатой более 500000. Таблица emp(id, name, dept, salary). Используйте GROUP BY и HAVING.",input_format="SQL",output_format="отдел, сумма",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: используйте GROUP BY с HAVING для фильтрации агрегатов"}],hidden_tests=[{"input":"check","expected":"HAVING"}]),
        TaskTemplate(title="SQL: UPDATE с подзапросом",domain=TaskDomain.SQL,level=DifficultyLevel.SENIOR,description="Напишите SQL-запрос UPDATE, который увеличивает зарплату на 10% сотрудникам, чей отдел имеет более 5 человек. Таблица emp(id, name, dept, salary).",input_format="SQL",output_format="UPDATE запрос",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: используйте UPDATE с подзапросом WHERE dept IN (SELECT ...)"}],hidden_tests=[{"input":"check","expected":"UPDATE"}]),
        TaskTemplate(title="Pandas: обработка пропущенных значений",domain=TaskDomain.PANDAS,level=DifficultyLevel.JUNIOR,description="Напишите Python-код, который загружает CSV-файл data.csv, заполняет пропущенные значения в столбце price средним значением и выводит количество оставшихся NaN.",input_format="код Python",output_format="количество NaN",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: .fillna(df[col].mean()) для замены пропусков средним"}],hidden_tests=[{"input":"check","expected":"fillna"}]),
        TaskTemplate(title="Pandas: merge двух таблиц",domain=TaskDomain.PANDAS,level=DifficultyLevel.MIDDLE,description="Напишите Python-код, который объединяет два DataFrame (orders и customers) по столбцу customer_id с помощью merge. Выведите итоговую таблицу.",input_format="код Python",output_format="merged DataFrame",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: pd.merge(df1, df2, on=ключ, how=left)"}],hidden_tests=[{"input":"check","expected":"merge"}]),
        TaskTemplate(title="Расчёт юнит-экономики",domain=TaskDomain.METRICS,level=DifficultyLevel.MIDDLE,description="Даны: стоимость привлечения клиента (CAC), средний чек (AOV), количество покупок в год (freq), маржинальность (margin). Вычислите LTV = AOV × freq × margin и ROI = (LTV - CAC) / CAC × 100%. Выведите LTV и ROI через пробел.",input_format="CAC AOV freq margin",output_format="LTV ROI%",visible_tests=[{"input":"1000 5000 4 0.3","expected":"6000.0 500.0"}],hidden_tests=[{"input":"500 2000 2 0.5","expected":"2000.0 300.0"}],reference_solution="cac,aov,freq,margin=map(float,input().split())\nltv=aov*freq*margin\nroi=(ltv-cac)/cac*100\nprint(ltv,roi)"),

        # === DEVOPS: дополнительные Docker/Bash/CI ===
        TaskTemplate(title="Docker: healthcheck",domain=TaskDomain.DOCKER,level=DifficultyLevel.MIDDLE,description="Напишите Dockerfile для Node.js-приложения с HEALTHCHECK. Проверка: curl -f http://localhost:3000/health каждые 30 секунд, таймаут 10 секунд, 3 попытки.",input_format="Dockerfile",output_format="Dockerfile с HEALTHCHECK",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: HEALTHCHECK --interval=30s --timeout=10s --retries=3 CMD curl ..."}],hidden_tests=[{"input":"check","expected":"HEALTHCHECK"}]),
        TaskTemplate(title="Bash: парсинг логов",domain=TaskDomain.BASH,level=DifficultyLevel.MIDDLE,description="Напишите bash-команду, которая из файла access.log выводит топ-5 IP-адресов по количеству запросов. Формат лога: IP - - [date] 'request' status. Используйте awk, sort, uniq.",input_format="bash",output_format="топ-5 IP",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: awk + sort + uniq -c + sort -rn + head -5"}],hidden_tests=[{"input":"check","expected":"uniq"}]),
        TaskTemplate(title="Docker Compose: Redis + App",domain=TaskDomain.DOCKER,level=DifficultyLevel.MIDDLE,description="Напишите docker-compose.yml с двумя сервисами: app (Python, build из текущей папки, порт 8000, зависит от redis) и redis (образ redis:7-alpine, порт 6379).",input_format="YAML",output_format="docker-compose.yml",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: два сервиса в services, depends_on для зависимости"}],hidden_tests=[{"input":"check","expected":"depends_on"}]),
        TaskTemplate(title="Bash: мониторинг диска",domain=TaskDomain.BASH,level=DifficultyLevel.JUNIOR,description="Напишите bash-команду, которая выводит использование диска в процентах для корневого раздела /. Используйте df и awk.",input_format="bash",output_format="процент",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: df -h / и awk для извлечения процента"}],hidden_tests=[{"input":"check","expected":"df"}]),
        TaskTemplate(title="K8s: Service и Ingress",domain=TaskDomain.YAML_CONFIG,level=DifficultyLevel.SENIOR,description="Напишите YAML-манифест Kubernetes Service (ClusterIP, порт 80, target 8080) и Ingress для хоста app.example.com.",input_format="YAML",output_format="Service + Ingress",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: kind: Service (ClusterIP, ports) + kind: Ingress (rules, host)"}],hidden_tests=[{"input":"check","expected":"Ingress"}]),

        # === QA: дополнительные тесты ===
        TaskTemplate(title="pytest: фикстуры и параметризация",domain=TaskDomain.PYTEST,level=DifficultyLevel.MIDDLE,description="Напишите pytest-тест с фикстурой @pytest.fixture, которая создаёт список [1,2,3], и параметризованный тест @pytest.mark.parametrize, проверяющий функцию is_even(n) для значений 2, 4, 6.",input_format="Python pytest",output_format="тест с fixture и parametrize",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: @pytest.fixture + @pytest.mark.parametrize для нескольких значений"}],hidden_tests=[{"input":"check","expected":"parametrize"}]),
        TaskTemplate(title="pytest: mock внешнего API",domain=TaskDomain.PYTEST,level=DifficultyLevel.SENIOR,description="Напишите pytest-тест, который мокает внешний HTTP-запрос с помощью unittest.mock.patch. Функция get_user(id) вызывает requests.get. Проверьте, что возвращается корректный JSON.",input_format="Python pytest",output_format="тест с mock",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: @patch(requests.get) + Mock(json=lambda: {...})"}],hidden_tests=[{"input":"check","expected":"patch"}]),
        TaskTemplate(title="Selenium: авторизация на сайте",domain=TaskDomain.SELENIUM,level=DifficultyLevel.MIDDLE,description="Напишите Selenium-скрипт авторизации: открыть страницу /login, ввести email и пароль в поля #email и #password, нажать кнопку #submit, проверить редирект на /dashboard.",input_format="Python Selenium",output_format="скрипт авторизации",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: driver.get() -> find_element(By.ID) -> send_keys() -> click() -> assert"}],hidden_tests=[{"input":"check","expected":"find_element"}]),
        TaskTemplate(title="Составление чек-листа тестирования API",domain=TaskDomain.TESTING,level=DifficultyLevel.JUNIOR,description="Составьте чек-лист тестирования REST API эндпоинта POST /api/users (создание пользователя). Опишите минимум 5 тест-кейсов: позитивный сценарий, пустые поля, дубликат email, невалидный формат, проверка ответа.",input_format="текст",output_format="чек-лист",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: TC-позитивный (201), TC-валидация (422), TC-дубликат (409), TC-auth (401)"}],hidden_tests=[{"input":"check","expected":"TC"}]),
        TaskTemplate(title="Тест-план для корзины интернет-магазина",domain=TaskDomain.TESTING,level=DifficultyLevel.MIDDLE,description="Составьте тест-план для функционала корзины: добавление товара, изменение количества, удаление, применение промокода, оформление заказа. Минимум 8 тест-кейсов.",input_format="текст",output_format="тест-план",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: 8 TC — добавление, удаление, количество, промокод, оформление"}],hidden_tests=[{"input":"check","expected":"TC"}]),

        # === DATA SCIENCE: дополнительные ML ===
        TaskTemplate(title="sklearn: разделение данных train/test",domain=TaskDomain.SKLEARN,level=DifficultyLevel.JUNIOR,description="Напишите Python-код, который разделяет данные X, y на обучающую и тестовую выборки (80/20) с помощью train_test_split. random_state=42. Выведите размеры выборок.",input_format="Python sklearn",output_format="размеры train/test",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: train_test_split(X, y, test_size=0.2, random_state=42)"}],hidden_tests=[{"input":"check","expected":"train_test_split"}]),
        TaskTemplate(title="sklearn: кросс-валидация модели",domain=TaskDomain.SKLEARN,level=DifficultyLevel.MIDDLE,description="Напишите Python-код, который выполняет 5-фолдовую кросс-валидацию RandomForestClassifier на данных X, y. Выведите среднее значение accuracy и стандартное отклонение.",input_format="Python sklearn",output_format="mean ± std accuracy",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: cross_val_score(модель, X, y, cv=5) и scores.mean()"}],hidden_tests=[{"input":"check","expected":"cross_val_score"}]),
        TaskTemplate(title="Обработка категориальных признаков",domain=TaskDomain.DATA_PROCESSING,level=DifficultyLevel.MIDDLE,description="Напишите Python-код, который выполняет One-Hot Encoding столбца 'color' в DataFrame с помощью pd.get_dummies(). Выведите названия новых столбцов.",input_format="Python pandas",output_format="новые столбцы",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: pd.get_dummies(df, columns=[столбец])"}],hidden_tests=[{"input":"check","expected":"get_dummies"}]),
        TaskTemplate(title="Матрица корреляций",domain=TaskDomain.DATA_PROCESSING,level=DifficultyLevel.JUNIOR,description="Напишите Python-код, который вычисляет матрицу корреляций для DataFrame и выводит пары признаков с корреляцией выше 0.8.",input_format="Python pandas",output_format="пары признаков",reference_solution="# решение",visible_tests=[{"input":"example","expected":"Подсказка: df.corr() для матрицы корреляций, фильтрация > 0.8"}],hidden_tests=[{"input":"check","expected":"corr"}]),
        ]
        for t in tpls: db.add(t)
        await db.flush()
        logger.info(f"Created {len(tpls)} task templates")



        # Demo interviews with FULL data (tasks, submissions, chat, anticheat)
        scores = [85, 62, 92, 55, 78, 88]
        recs = ['hire','maybe','hire','maybe','hire','hire']
        lvls = [DifficultyLevel.MIDDLE, DifficultyLevel.JUNIOR, DifficultyLevel.SENIOR, DifficultyLevel.JUNIOR, DifficultyLevel.MIDDLE, DifficultyLevel.SENIOR]
        summaries = ["Отличные алгоритмические навыки. Уверенно решает задачи.",
                     "Хорошая база, нужна практика в алгоритмах.",
                     "Глубокие знания системного дизайна. Рекомендован на Senior.",
                     "Средний уровень, нужна подготовка по графам.",
                     "Уверенный Middle. Хорошо решает SQL.",
                     "Превосходные навыки ML и анализа данных."]

        specs = ['developer','developer','developer','analyst','analyst','data_science']

        for i, cand in enumerate(cands):
            iv = Interview(user_id=cand.id, status=InterviewStatus.COMPLETED, level=lvls[i],
                           total_score=scores[i], total_tasks=5, completed_tasks=5,
                           started_at=now-timedelta(days=10-i, hours=2), finished_at=now-timedelta(days=10-i, hours=1),
                           ai_summary=summaries[i], ai_recommendation=recs[i], specialty=specs[i])
            db.add(iv); await db.flush()

            # Tasks + submissions
            for j in range(5):
                tpl = tpls[min(j + (i % 3) * 2, len(tpls)-1)]
                task = Task(interview_id=iv.id, template_id=tpl.id, title=tpl.title, description=tpl.description,
                            domain=tpl.domain, level=tpl.level, order_number=j+1,
                            visible_tests=tpl.visible_tests, hidden_tests=tpl.hidden_tests)
                db.add(task); await db.flush()

                code = f"# Решение задачи: {tpl.title}\n{tpl.reference_solution}" if scores[i] > 50 else f"# Попытка\nprint('hello')"
                sub_score = max(0, scores[i] + (j-2)*5 + ((-1)**j)*3)
                sub = Submission(task_id=task.id, code=code, language="python", is_final=True,
                                 score=min(100, sub_score), passed_visible=1 if sub_score>40 else 0, total_visible=2,
                                 passed_hidden=1 if sub_score>60 else 0, total_hidden=2, execution_time_ms=15+j*5)
                db.add(sub)

            # Chat messages (realistic dialog)
            dialogs = [
                ("Привет! Готов начать собеседование.", "candidate"),
                ("Здравствуйте! Давайте начнём. Прочитайте условие первой задачи и расскажите свой подход.", "ai"),
                ("Я думаю использовать цикл для перебора элементов массива.", "candidate"),
                ("Хороший подход! Какая будет временная сложность вашего решения?", "ai"),
                ("O(n) — один проход по массиву.", "candidate"),
                ("Верно! Попробуйте реализовать и запустить тесты.", "ai"),
            ]
            for k, (msg, sender) in enumerate(dialogs):
                db.add(ChatMessage(interview_id=iv.id, task_id=task.id, sender=sender, content=msg,
                                   timestamp=now-timedelta(days=10-i, hours=2)+timedelta(minutes=k*3)))

            # Anticheat events
            if i % 3 == 0:  # Every 3rd candidate has suspicious activity
                db.add(AnticheatEvent(interview_id=iv.id, event_type="tab_switch", severity=0.2,
                                       timestamp=now-timedelta(days=10-i, hours=1, minutes=30)))
            if i % 4 == 0:
                db.add(AnticheatEvent(interview_id=iv.id, event_type="paste", severity=0.4,
                                       details={"length": 150},
                                       timestamp=now-timedelta(days=10-i, hours=1, minutes=15)))

        # Direct messages (HR <-> Candidates)
        msg_data = [
            (hr1.id, cands[0].id, "Здравствуйте, Дмитрий! Мы рассмотрели ваше собеседование. Результаты отличные!"),
            (cands[0].id, hr1.id, "Спасибо! Когда можно ожидать следующий этап?"),
            (hr1.id, cands[0].id, "Мы готовим оффер, ожидайте в течение 2-3 рабочих дней."),
            (hr1.id, cands[1].id, "Елена, благодарим за участие. Предлагаем пройти дополнительное собеседование."),
            (cands[1].id, hr1.id, "Да, конечно! Когда удобно?"),
            (hr2.id, cands[3].id, "Анна, по результатам собеседования рекомендуем подтянуть алгоритмы."),
            (cands[3].id, hr2.id, "Спасибо за обратную связь! Буду готовиться."),
            (hr2.id, cands[4].id, "Сергей, отличный результат! Приглашаем на финальное собеседование."),
            (cands[4].id, hr2.id, "Благодарю! С удовольствием."),
            (hr2.id, cands[5].id, "Мария, ваш уровень впечатляет. Готовим предложение для вас."),
        ]
        for k, (from_id, to_id, content) in enumerate(msg_data):
            db.add(DirectMessage(from_user_id=from_id, to_user_id=to_id, content=content,
                                  is_read=k<5, timestamp=now-timedelta(days=5)+timedelta(hours=k)))

        # Support ticket demo — assigned to support agents
        db.add(SupportTicket(user_id=cands[2].id, subject="Ошибка при запуске тестов", message="При нажатии 'Запустить' ничего не происходит.",
                              category="bug", priority="high", status="open", assigned_to=sup1.id))
        db.add(SupportTicket(user_id=hr1.id, subject="Как экспортировать отчёт?", message="Не могу найти кнопку экспорта PDF.",
                              category="question", priority="low", status="open", assigned_to=sup2.id))
        db.add(SupportTicket(user_id=cands[0].id, subject="Не приходит код на email", message="Зарегистрировался, но код не пришёл. Проверил спам.",
                              category="account", priority="medium", status="open", assigned_to=sup1.id))
        db.add(SupportTicket(user_id=cands[1].id, subject="Код не компилируется", message="Написал решение на Python, нажал запуск — ошибка SyntaxError.",
                              category="bug", priority="high", status="open", assigned_to=sup2.id))
        db.add(SupportTicket(user_id=hr2.id, subject="Добавить новое направление", message="Можно ли добавить направление Mobile для собеседований?",
                              category="feature", priority="low", status="open", assigned_to=sup1.id))

        # === Additional companies ===
        comp3 = Company(name="CloudTech Solutions", description="Облачные сервисы и DevOps", website="https://cloudtech.ru")
        comp4 = Company(name="DataMind Analytics", description="Аналитика больших данных и ML", website="https://datamind.ru")
        db.add(comp3); db.add(comp4); await db.flush()

        # === Additional HR users ===
        hr3 = User(email="hr3@company.ru", password_hash=hash_password("HrCloud2024!"), role=UserRole.HR, full_name="Козлова Анна Сергеевна", company_id=comp3.id, phone="+7(903)111-22-33", email_verified=True)
        hr4 = User(email="hr4@company.ru", password_hash=hash_password("HrData2024!"), role=UserRole.HR, full_name="Морозов Дмитрий Алексеевич", company_id=comp4.id, phone="+7(905)444-55-66", email_verified=True)
        db.add(hr3); db.add(hr4); await db.flush()

        # === Additional vacancies ===
        db.add(Vacancy(title="DevOps-инженер", specialty="devops", level="middle", description="Настройка CI/CD, Docker, Kubernetes. Мониторинг и автоматизация инфраструктуры.", company_id=comp3.id, salary_from=180000, salary_to=280000))
        db.add(Vacancy(title="Data Scientist", specialty="data_science", level="senior", description="Разработка ML-моделей, анализ данных, A/B тестирование, построение рекомендательных систем.", company_id=comp4.id, salary_from=250000, salary_to=400000))
        db.add(Vacancy(title="QA Automation Engineer", specialty="qa", level="middle", description="Автоматизация тестирования на pytest + Selenium. Написание тест-кейсов и CI интеграция.", company_id=comp3.id, salary_from=150000, salary_to=230000))
        db.add(Vacancy(title="Frontend React Developer", specialty="developer", level="junior", description="Разработка UI на React, TypeScript, работа с REST API и State Management.", company_id=comp4.id, salary_from=80000, salary_to=140000))
        await db.flush()

        # === Pre-fill messages between HR and candidates ===
        db.add(DirectMessage(from_user_id=hr1.id, to_user_id=cands[0].id, content="Добрый день! Мы рассмотрели ваши результаты собеседования. Хотели бы пригласить вас на следующий этап.", is_read=False))
        db.add(DirectMessage(from_user_id=cands[0].id, to_user_id=hr1.id, content="Здравствуйте! Спасибо, в какое время удобно?", is_read=False))
        db.add(DirectMessage(from_user_id=hr1.id, to_user_id=cands[1].id, content="Здравствуйте! Благодарим за участие в собеседовании. К сожалению, мы остановили выбор на другом кандидате.", is_read=False))
        db.add(DirectMessage(from_user_id=hr2.id, to_user_id=cands[2].id, content="Добрый день! Приглашаем вас на техническое собеседование по вакансии Python-разработчик.", is_read=False))
        db.add(DirectMessage(from_user_id=cands[2].id, to_user_id=hr2.id, content="Здравствуйте! Спасибо за приглашение, я готова.", is_read=True))
        db.add(DirectMessage(from_user_id=hr1.id, to_user_id=cands[3].id, content="Поздравляем! По итогам собеседования мы хотели бы предложить вам позицию в нашей команде!", is_read=False))
        db.add(DirectMessage(from_user_id=cands[0].id, to_user_id=hr2.id, content="Добрый день, подскажите по вакансии аналитика — ещё актуально?", is_read=False))
        # More messages for demo
        db.add(DirectMessage(from_user_id=hr3.id, to_user_id=cands[0].id, content="Здравствуйте! Рассматриваем вашу кандидатуру на позицию DevOps-инженер в CloudTech Solutions.", is_read=False))
        db.add(DirectMessage(from_user_id=hr4.id, to_user_id=cands[3].id, content="Добрый день! Приглашаем вас на собеседование по Data Science в DataMind Analytics.", is_read=False))
        db.add(DirectMessage(from_user_id=cands[3].id, to_user_id=hr4.id, content="Спасибо! Когда можно пройти?", is_read=True))
        db.add(DirectMessage(from_user_id=hr1.id, to_user_id=cands[4].id, content="📋 Вакансия: Python-разработчик (TechVision Labs)\n→ vacancy/1", is_read=False))
        db.add(DirectMessage(from_user_id=hr2.id, to_user_id=cands[5].id, content="📋 Вакансия: SQL-аналитик (DataFlow Solutions)\n→ vacancy/3", is_read=False))
        await db.flush()

        # === Notifications for all roles ===
        from app.models import Notification
        # HR notifications
        db.add(Notification(user_id=hr1.id, type="interview_complete", title="Собеседование завершено", message=f"{cands[0].full_name} завершил собеседование — 85%", link="/hr/dashboard"))
        db.add(Notification(user_id=hr1.id, type="interview_complete", title="Собеседование завершено", message=f"{cands[1].full_name} завершил собеседование — 62%", link="/hr/dashboard"))
        db.add(Notification(user_id=hr2.id, type="new_candidate", title="Новый кандидат", message=f"{cands[2].full_name} откликнулся на вакансию", link="/hr/dashboard"))
        # Candidate notifications
        db.add(Notification(user_id=cands[0].id, type="offer", title="Вам поступил оффер!", message="TechVision Labs предлагает вам позицию Python-разработчик", link="/messages"))
        db.add(Notification(user_id=cands[0].id, type="new_message", title="Новое сообщение", message="HR-менеджер написал вам", link="/messages"))
        db.add(Notification(user_id=cands[1].id, type="interview_result", title="Результаты собеседования", message="Ваш результат: 62%. Рекомендация: доп. подготовка", link="/results"))
        db.add(Notification(user_id=cands[2].id, type="vacancy_new", title="Новая вакансия", message="Python-разработчик (Middle) в TechVision Labs", link="/vacancies"))
        # Admin notifications
        db.add(Notification(user_id=admin.id, type="system", title="Система запущена", message="AI Interview Platform v1.0 успешно развёрнута", link="/admin"))
        db.add(Notification(user_id=admin.id, type="system_error", title="AI-модуль", message="Требуется настройка API-ключа LLM провайдера", link="/admin"))
        # Support notifications
        db.add(Notification(user_id=sup1.id, type="new_ticket", title="Новое обращение", message=f"Тикет от {cands[2].full_name}: Ошибка при запуске тестов", link="/support"))
        db.add(Notification(user_id=sup2.id, type="new_ticket", title="Новое обращение", message=f"Тикет от {hr1.full_name}: Как экспортировать отчёт?", link="/support"))
        await db.flush()

        # Audit log
        db.add(AuditLog(user_id=admin.id, action="system_start", details={"version": "1.0.0"}))
        db.add(AuditLog(user_id=hr1.id, action="login", details={"ip": "192.168.1.100"}))
        db.add(AuditLog(user_id=hr1.id, action="decision_hire", details={"candidate_id": cands[0].id}))
        db.add(AuditLog(user_id=hr2.id, action="login", details={"ip": "192.168.1.101"}))
        db.add(AuditLog(user_id=cands[0].id, action="login", details={"ip": "10.0.0.5"}))
        db.add(AuditLog(user_id=cands[1].id, action="login", details={"ip": "10.0.0.6"}))
        db.add(AuditLog(user_id=admin.id, action="block_user", details={"target_user_id": 99, "reason": "spam"}))

        await db.commit()
        logger.info("Database seeded with full demo data!")
